// <auto-generated />
using System;
using CovoitEco.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovoitEco.Core.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Annonce", b =>
                {
                    b.Property<int>("ANN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ANN_Id"));

                    b.Property<DateTime>("ANN_DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ANN_HeureArrive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ANN_HeureDepart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ANN_LocaliteArrive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANN_LocaliteDepart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ANN_OPT_Id")
                        .HasColumnType("int");

                    b.Property<float>("ANN_Prix")
                        .HasColumnType("real");

                    b.Property<int>("ANN_STATANN_Id")
                        .HasColumnType("int");

                    b.Property<int>("ANN_UTL_Id")
                        .HasColumnType("int");

                    b.Property<int>("ANN_VEH_Id")
                        .HasColumnType("int");

                    b.HasKey("ANN_Id");

                    b.ToTable("Annonce", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Facture", b =>
                {
                    b.Property<int>("FACT_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FACT_Id"));

                    b.Property<DateTime>("FACT_DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FACT_DatePayment")
                        .HasColumnType("datetime2");

                    b.Property<int>("FACT_RES_Id")
                        .HasColumnType("int");

                    b.Property<bool>("FACT_Resolus")
                        .HasColumnType("bit");

                    b.HasKey("FACT_Id");

                    b.ToTable("Facture", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Modele", b =>
                {
                    b.Property<int>("MOD_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MOD_id"));

                    b.Property<string>("MOD_Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOD_Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MOD_NombrePlace")
                        .HasColumnType("int");

                    b.Property<int>("MOD_NormeEuro")
                        .HasColumnType("int");

                    b.HasKey("MOD_id");

                    b.ToTable("Modele", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Note", b =>
                {
                    b.Property<int>("NOT_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NOT_Id"));

                    b.Property<float>("NOT_Cotation")
                        .HasColumnType("real");

                    b.Property<int>("NOT_UTL_Id")
                        .HasColumnType("int");

                    b.HasKey("NOT_Id");

                    b.ToTable("Note", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NOTIF_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NOTIF_Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ROL_UTL_Id")
                        .HasColumnType("int");

                    b.HasKey("NOTIF_Id");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Option", b =>
                {
                    b.Property<int>("OPT_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OPT_Id"));

                    b.Property<string>("OPT_Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OPT_Id");

                    b.ToTable("Option", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Recherche", b =>
                {
                    b.Property<int>("RECH_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RECH_Id"));

                    b.Property<DateTime>("RECH_DateEnregistrement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RECH_HeureDepart")
                        .HasColumnType("datetime2");

                    b.Property<string>("RECH_LocaliteArrvie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RECH_LocaliteDepart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RECH_UTL_Id")
                        .HasColumnType("int");

                    b.HasKey("RECH_Id");

                    b.ToTable("Recherche", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("RES_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RES_Id"));

                    b.Property<int>("RES_ANN_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("RES_DateReservation")
                        .HasColumnType("datetime2");

                    b.Property<int>("RES_STATRES_Id")
                        .HasColumnType("int");

                    b.Property<int>("RES_UTL_Id")
                        .HasColumnType("int");

                    b.HasKey("RES_Id");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Role", b =>
                {
                    b.Property<int>("ROL_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ROL_Id"));

                    b.Property<string>("ROL_Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ROL_Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.StatutAnnonce", b =>
                {
                    b.Property<int>("STATANN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STATANN_Id"));

                    b.Property<int>("STATANN_Libelle")
                        .HasColumnType("int");

                    b.HasKey("STATANN_Id");

                    b.ToTable("StatutAnnonce", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.StatutReservation", b =>
                {
                    b.Property<int>("STATRES_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STATRES_Id"));

                    b.Property<string>("STATRES_Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STATRES_Id");

                    b.ToTable("StatutResevation", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("UTL_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UTL_Id"));

                    b.Property<string>("UTL_Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UTL_Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UTL_ROL_Id")
                        .HasColumnType("int");

                    b.Property<string>("UTL_Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UTL_Id");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("CovoitEco.Core.Domain.Entities.Vehicule", b =>
                {
                    b.Property<int>("VEH_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VEH_Id"));

                    b.Property<string>("VEH_Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VEH_Immatriculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VEH_MOD_Id")
                        .HasColumnType("int");

                    b.Property<int>("VEH_UTL_Id")
                        .HasColumnType("int");

                    b.HasKey("VEH_Id");

                    b.ToTable("Vehicule", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
